### ISSUE TITLE
How does the file download work?

### ISSUE THREAD

**Issue by emresaracoglu** [ToshY/BunnyNet-PHP#37]
Hello,

Thank you for your repo. 
Direct friend downloading does not start. with "var_dump", the codes of the file are displayed. How can I start the direct download? Can you help with this too?

`$bunnyEdgeStorage->downloadFile('my-storage-zone-1', 'css', 'new-custom.css');`

Thank you

**Comment by ToshY** [comment]
Hello @emresaracoglu 👋 

Could you clarify on what your current result is and what you're expecting to see?

As an example, I upload a file called `test.md` to my storagezone `toshy`, and then try to download it like and dump the result using Symfony's `dd()`:

```php
$result = $this->testStorageRequestUpload->downloadFile('toshy','','test.md');

dd($result);

array:3 [▼
  "content" => """
    # This Is A Test File
    
    Hello World
    """
  "headers" => array:7 [▶]
  "status" => array:2 [▶]
]
```

So the content of the file is available in the `content` key. 

Does this help?

**Comment by emresaracoglu** [comment]
Thank you for your answer. I think I got an error because I was trying to download a media file. It seems that your code is suitable for a TXT File or its derivatives, but what kind of structure do I need for media files?

**Comment by ToshY** [comment]
@emresaracoglu I've tested it with several file types, both plaintext as well as binary. So if you want to either get a PNG or MP4 file, it works the same way. The `content` key will just contain binary content then. You can write it to your filesystem with for example [fwrite](https://www.php.net/manual/en/function.fwrite.php).

```php
$result = $this->testStorageRequestUpload->downloadFile('toshy','','test.mp4');

// New file in writable binary mode
$fp = fopen('/app/awesome.mp4', 'wb');
fwrite($fp, $result['content']);
fclose($fp);
```
