### ISSUE TITLE
[Feature]: Stream API Upload Thumbnail

### ISSUE THREAD

**Issue by 2mann** [ToshY/BunnyNet-PHP#96]
### Description

Had a chat with Bunny support about uploading a video thumbnail, and it turns out they have an API for that, it's not in the Bunny API documentation yet. Here it is:

`curl --request POST \
  --url https://video.bunnycdn.com/library/id/videos/id/thumbnail \
  --header 'AccessKey: key' \
  --header 'Content-Type: image/png' \
  --data-binary @download.png`

**Comment by ToshY** [comment]
Hey @2mann 👋 

Do I understand it correctly if I say it's basically the same endpoint as [Set Thumbnail](https://docs.bunny.net/reference/video_setthumbnail), but instead of supplying a `thumbnailUrl` as query parameter, you're uploading the image directly (as body)?

**Comment by 2mann** [comment]
That's correct. This way the image is hosted with the video on Stream.

**Comment by ToshY** [comment]
Okay that's clear to me.

I will add this to the `4.0` milestone for now. [^explanation]

[^explanation]: While this would be a minor change, as it only requires either a new method or updating the current method to allow body contents, I first wish to fix #95, as this would improve the usability for passing body contents as string/stream.

**Comment by ToshY** [comment]
Hey @2mann 👋 

This has been released in [`4.0.0`](https://github.com/ToshY/BunnyNet-PHP/releases/tag/4.0.0). You can check the documentation section [Set Thumbnail (by body)](https://toshy.github.io/BunnyNet-PHP/stream-api/#set-thumbnail-by-body) on how to use it.

If you have questions or remarks, let me know 👌
